image:
  repository: registry-local.devops.svc.cluster.local/calculator
  tag: latest

ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "calculator.rojandinc.se"
    external-dns.alpha.kubernetes.io/target: tunnel.rojandinc.se
    nginx.ingress.kubernetes.io/enable-global-auth: "false"

  hosts:
    - host: calculator.rojandinc.se
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false
